#
# Copyright (c) 2024–2025, Daily
#
# SPDX-License-Identifier: BSD 2-Clause License
#

"""pipecat-call-agent - Pipecat Voice Agent

This bot uses a cascade pipeline: Speech-to-Text → LLM → Text-to-Speech

Generated by Pipecat CLI

Required AI services:
- Deepgram (Speech-to-Text)
- Ollama (LLM)
- Elevenlabs (Text-to-Speech)

Run the bot using::

    uv run bot.py
"""


from pipecat.pipeline.task import PipelineParams, PipelineTask
from pipecat.transports.smallwebrtc.transport import SmallWebRTCTransport
import aiofiles
from pipecat.transports.smallwebrtc.connection import SmallWebRTCConnection
from pipecat.services.deepgram.stt import DeepgramSTTService
# from pipecat.services.groq.stt import GroqSTTService
from pipecat.frames.frames import TranscriptionMessage, TranscriptionUpdateFrame
from pipecat.runner.types import SmallWebRTCRunnerArguments
from pipecat_tail.observer import TailObserver
from pipecat_whisker import WhiskerObserver
from pipecat.audio.turn.smart_turn.local_smart_turn_v3 import LocalSmartTurnAnalyzerV3
from pipecat.audio.vad.silero import SileroVADAnalyzer
from pipecat.processors.aggregators.llm_context import LLMContext
from pipecat.runner.types import WebSocketRunnerArguments
from pipecat.services.elevenlabs.tts import ElevenLabsTTSService
from pipecat.runner.types import RunnerArguments
from pipecat.audio.vad.vad_analyzer import VADParams
from pipecat.pipeline.pipeline import Pipeline
from pipecat.transports.websocket.fastapi import FastAPIWebsocketTransport, FastAPIWebsocketParams
from pipecat.processors.aggregators.llm_response_universal import LLMContextAggregatorPair
from pipecat.services.ollama.llm import OLLamaLLMService
import datetime
import wave
import io
from pipecat.transports.base_transport import BaseTransport
from pipecat.processors.audio.audio_buffer_processor import AudioBufferProcessor
from pipecat.runner.utils import parse_telephony_websocket
from loguru import logger
from pipecat.transports.base_transport import TransportParams
from pipecat.processors.transcript_processor import TranscriptProcessor
from pipecat.pipeline.runner import PipelineRunner
from dotenv import load_dotenv
from pipecat.serializers.plivo import PlivoFrameSerializer
import os
from pipecat.frames.frames import LLMRunFrame



load_dotenv(override=True)


async def save_audio_file(audio: bytes, filename: str, sample_rate: int, num_channels: int):
    """Save audio data to a WAV file."""
    if len(audio) > 0:
        with io.BytesIO() as buffer:
            with wave.open(buffer, "wb") as wf:
                wf.setsampwidth(2)
                wf.setnchannels(num_channels)
                wf.setframerate(sample_rate)
                wf.writeframes(audio)
            async with aiofiles.open(filename, "wb") as file:
                await file.write(buffer.getvalue())
        logger.info(f"Audio saved to {filename}")




async def run_bot(transport: BaseTransport):
    """Main bot logic."""
    logger.info("Starting bot")

    # Speech-to-Text service
    stt = DeepgramSTTService(api_key=os.getenv("DEEPGRAM_API_KEY"))
    # stt = GroqSTTService(api_key=os.getenv("GROQ_API_KEY"))


    # Text-to-Speech service
    tts = ElevenLabsTTSService(
            api_key=os.getenv("ELEVENLABS_API_KEY"),
            voice_id=os.getenv("ELEVENLABS_VOICE_ID")
        )


    # LLM service
    llm = OLLamaLLMService(model=os.getenv("OLLAMA_MODEL"))

    # Video service (avatar)

    messages = [
        {
            "role": "system",
            "content": "You are a friendly AI assistant. Respond naturally and keep your answers conversational.",
        },
    ]

    context = LLMContext(messages)
    context_aggregator = LLMContextAggregatorPair(context)


    # Audio recording
    audio_buffer = AudioBufferProcessor()

    # Transcription processor
    transcript_processor = TranscriptProcessor()



    # Pipeline - assembled from reusable components
    pipeline = Pipeline([
        transport.input(),

        
        stt,

        transcript_processor.user(),

        context_aggregator.user(),

        llm,

        tts,

        
        transport.output(),

        transcript_processor.assistant(),

        audio_buffer,

        context_aggregator.assistant(),

    ])


    task = PipelineTask(
        pipeline,
        params=PipelineParams(
            enable_metrics=True,
            enable_usage_metrics=True,
            audio_in_sample_rate=8000,
            audio_out_sample_rate=8000,
        ),
        observers=[
            WhiskerObserver(pipeline),
            TailObserver(),
        ],
    )

    @transport.event_handler("on_client_connected")
    async def on_client_connected(transport, client):
        logger.info("Client connected")
        # Start recording audio
        await audio_buffer.start_recording()
        # Kick off the conversation
        messages.append({"role": "system", "content": "Say hello and briefly introduce yourself."})
        await task.queue_frames([LLMRunFrame()])

    @transport.event_handler("on_client_disconnected")
    async def on_client_disconnected(transport, client):
        logger.info("Client disconnected")
        await task.cancel()


    @transcript_processor.event_handler("on_transcript_update")
    async def on_transcript_update(processor: TranscriptProcessor, frame: TranscriptionUpdateFrame):
        for msg in frame.messages:
            if isinstance(msg, TranscriptionMessage):
                timestamp = f"[{msg.timestamp}] " if msg.timestamp else ""
                line = f"{timestamp}{msg.role}: {msg.content}"
                logger.info(f"Transcript: {line}")


    @audio_buffer.event_handler("on_audio_data")
    async def on_audio_data(buffer, audio, sample_rate, num_channels):
        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"recordings/merged_{timestamp}.wav"
        os.makedirs("recordings", exist_ok=True)
        await save_audio_file(audio, filename, sample_rate, num_channels)


    runner = PipelineRunner(handle_sigint=False)

    await runner.run(task)


async def bot(runner_args: RunnerArguments):
    """Main bot entry point."""

    transport = None

    match runner_args:
        case SmallWebRTCRunnerArguments():
            webrtc_connection: SmallWebRTCConnection = runner_args.webrtc_connection

            transport = SmallWebRTCTransport(
                webrtc_connection=webrtc_connection,
                params=TransportParams(
                    audio_in_enabled=True,
                    audio_out_enabled=True,
                    vad_analyzer=SileroVADAnalyzer(params=VADParams(stop_secs=0.2)),
                    turn_analyzer=LocalSmartTurnAnalyzerV3(),
                ),
            )
        case WebSocketRunnerArguments():
            # Parse Plivo websocket
            _, call_data = await parse_telephony_websocket(runner_args.websocket)

            serializer = PlivoFrameSerializer(
                stream_id=call_data["stream_id"],
                call_id=call_data["call_id"],
                auth_id=os.getenv("PLIVO_AUTH_ID", ""),
                auth_token=os.getenv("PLIVO_AUTH_TOKEN", ""),
            )

            transport = FastAPIWebsocketTransport(
                websocket=runner_args.websocket,
                params=FastAPIWebsocketParams(
                    audio_in_enabled=True,
                    audio_out_enabled=True,
                    add_wav_header=False,
                    vad_analyzer=SileroVADAnalyzer(params=VADParams(stop_secs=0.2)),
                    turn_analyzer=LocalSmartTurnAnalyzerV3(),
                    serializer=serializer,
                ),
            )
        case _:
            logger.error(f"Unsupported runner arguments type: {type(runner_args)}")
            return

    await run_bot(transport)


if __name__ == "__main__":
    from pipecat.runner.run import main

    main()